yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self) -> str:
        return self.title

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group
# Create your views here.


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {'title': title,
               'posts': posts}
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = f'Записи группы {group.title}'
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'title': title,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    {% block title %}
    <title>Титульник не подключен...</title>
    {% endblock %}
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main> 
      {% block content %}
        <h1>Контект не подключен...</h1>
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
<div class="container">
    <a class="navbar-brand" href={% url 'posts:index' %}>
    <img src={% static 'img/logo.png' %} width="30" height="30" class="d-inline-block align-top" alt="">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
    <span style="color:red">Ya</span>tube
    </a>
</div>
</nav>   

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  <title>{{ title }}</title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>

    {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name}}
          </li>
          <li class=entry>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}


       

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  <title>{{title}}</title>
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{title}}</h1> 
  {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p> 
  
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}

</div>{% endblock %}